- name: play level variables
  hosts: local
  connection: local
  vars:
   COURSE: "DEVOPS WITH AWS"
   DURATION: "140HRS"
   TRAINER: "SIVAKUMAR REDDY"
  tasks:
   - name: print variables
     ansible.builtin.debug:
      msg: "COURSE is: {{COURSE}} ,TRAINER IS: {{TRAINER}}"