- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
   - name: print variables
     vars:
      COURSE: "ANSIBLE"
     tasks:
     ansible.builtin.debug:
      msg: "COURSE IS: {{COURSE}} ,TRAINER IS: {{TRAINER}}"